### ISSUE TITLE
Mongo serialization error

### ISSUE THREAD

**Issue by bradamelton** [bradamelton/saberfin.io#11]
Can't serialize a nested item: System.ArgumentException: .NET type SaberFin.Services cannot be mapped to a BsonValue.
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at MongoDB.Bson.BsonDocument.AddRange(IEnumerable`1 dictionary)
   at MongoDB.Bson.BsonDocument.AddRange(Dictionary`2 dictionary)
   at DBu.DBuMongoProvider.Save(Object obj, String[] searchProperties) in /mnt/f/github/DBu/DBu.Core/Providers/DBuMongoProvider.cs:line 241. This won't be added to the updates.

**Comment by bradamelton** [comment]
I think I fixed this. I will close unless I see it again.
